- type: startingGear
  id: CentcomFormalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommChameleon
    eyes: ClothingEyesGlassesCCDivHead
    gloves: ClothingHandsGlovesCombat
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponDisabler
    pocket2: WeaponRevolverMateba
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomInspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcomFormalDress
    shoes: ClothingShoesBootsJackFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommChameleon
    eyes: ClothingEyesGlassesCCDivHead
    gloves: ClothingHandsGlovesCombat
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    pocket1: WeaponDisabler
    pocket2: FlashlightSeclite
    suitstorage: OxygenTankFilled
  inhand:
  - BriefcaseCentcomInspector
- type: startingGear
# This loadout is meant for very specific circumstances, or if the relevant character will remain on CentComm.
# Due to the items inside, any character ON STATION with this loadout should have ERT Sec guards.
# This explicitly now targets a role as CC Security division
  id: CentcomOfficerGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommSecurityFormalWear
    back: ClothingBackpackSatchelHoldingCentcomOfficerFilled
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    mask: ClothingMaskGasCentcom
    neck: ClothingNeckCloakCCSDFireline
    outerClothing: ClothingOuterArmorCentcommChameleon
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesHudCCDivHead # Somehow missed this in the original outfits port...
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: CentcommVibrobladeSheathFilled
    pocket1: WeaponEnergyMagnumGunGreenshield
    pocket2: WeaponPistolStechkin
    suitstorage: WeaponRifleL10
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomSmartBorgiGear # they're cute and silly and I like them for harmless admemes (it should definitely only be admin controlled however)
  equipment:
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    mask: ClothingMaskWeldingGas
    outerClothing: ClothingOuterHardsuitERTEngineer # Well rounded and can fit in the bag! Amazing!
    eyes: ClothingEyesGlassesCCDivHead
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: ClothingBeltChiefEngineerFilled
    suitstorage: OxygenTankFilled
  inhand:
  - MindShieldImplanter # Turns out that yes, they can recieve implants. Probably good to have them mindshielded.
  - DeathRattleImplanterCentcomm
