- type: startingGear
  id: CentcomFormalGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCentcomFormal
    back: ClothingBackpackSatchelHoldingCentcomFormalFilled
    shoes: ClothingShoesBootsCombatFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    id: CentCommDivisionPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: BoxFolderCentComClipboardThreePapers
    pocket1: WeaponDisabler
    pocket2: WeaponRevolverMateba
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm

- type: startingGear
  id: CentcomInspectorGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcomFormalDress
    shoes: ClothingShoesBootsJackFilled
    mask: ClothingMaskGasCentcom
    outerClothing: ClothingOuterArmorCentcommCarapace
    eyes: ClothingEyesGlassesCentComm
    gloves: ClothingHandsGlovesCombat
    id: CentcomPDA
    ears: ClothingHeadsetAltCentComDivHead
    pocket1: WeaponDisabler
    pocket2: FlashlightSeclite
    suitstorage: OxygenTankFilled
  inhand:
  - BriefcaseCentcomInspector
- type: startingGear
#This became very specific to Semper, so I'm just gona mark it as the relevant name
  id: CentcomSecDivHeadGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtCentcommSecurityFormalWear
    back: ClothingBackpackHoldingCentcomOfficerFilled
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHeadHatCentcomcap
    mask: ClothingMaskGasCentcom
    neck: ClothingNeckCloakCCSDFireline
    outerClothing: ClothingOuterArmorCentcommCarapace
    gloves: ClothingHandsGlovesCombat
    eyes: ClothingEyesHudCCDivHead
    id: CentCommDivisionPDA
    ears: ClothingHeadsetAltCentComDivHead
    belt: CentcommVibrobladeSheathFilled
    pocket1: WeaponEnergyMagnumGunGreenshield
    pocket2: WeaponPistolStechkin
    suitstorage: WeaponRifleL10
  inhand:
  - MindShieldImplanter
  - DeathRattleImplanterCentcomm
