- type: job
  id: NanotrasenCareerTrainer
  name: job-name-nct
  description: job-description-nct
  playTimeTracker: JobNanotrasenCareerTrainer
  requirements:
    #- !type:MentorFlagRequirement # Ronstation: Flags for mentors/staff (DOES NOT WORK, MAKING SEPERATE PR)
    - !type:TraitsRequirement
      traits:
        - Iterator
        #- Muted Ronstation: No, we don't hate our folks with disabilities.
      inverted: true
  whitelisted: true # Ronstation: This role is meant for mentors, and should only be available to them.
  startingGear: NanotrasenCareerTrainerGear
  icon: JobIconNanotrasenCareerTrainer
  rules: job-rules-corporate-aligned
  supervisors: job-supervisors-nt-personnel
  displayWeight: 2
  overrideConsoleVisibility: false
  joinNotifyCrew: true
  access:
    - Lawyer
    - Command
    - Service
    - Maintenance
    - Theatre
    - External
    - Engineering
    - Research
    - Security
    - Cargo
    - Medical
    - IAA
  special:
    - !type:AddImplantSpecial
      implants: [MindShieldImplant]
    - !type:AddComponentSpecial
      components:
        - type: NoObjectiveTarget
        - type: NCTAgent

- type: startingGear
  id: NanotrasenCareerTrainerGear
  equipment:
    id: NanoTrasenCareerTrainerPDA
    ears: ClothingHeadsetNCT
    neck: Whistle
    pocket1: nctdatachip
    pocket2: PinpointerUniversal
    belt: BoxFolderNanoTrasenClipboard
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCoatNCT
  storage:
    back:
    - Flash

- type: chameleonOutfit
  id: NanotrasenCareerTrainerChameleonOutfit
  job: NanotrasenCareerTrainer
  hasMindShield: true
  equipment:
    outerClothing: ClothingOuterCoatNCT
